### ISSUE TITLE
Non functional with Plone 4.1b1

### ISSUE THREAD

**Issue by khink** [collective/collective.portlet.content#4]
(http://plone.org/products/collective.portlet.content/issues/4)

Version 1.6

Traceback (most recent call last):
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/Startup/run.py", line 72, in <module>
    run()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/Startup/run.py", line 21, in run
    starter.prepare()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/Startup/**init**.py", line 86, in prepare
    self.startZope()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/Startup/**init**.py", line 259, in startZope
    Zope2.startup()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/**init**.py", line 47, in startup
    _startup()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 651, in file
    include(context, name, package)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 550, in include
    processxmlfile(f, context)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 382, in processxmlfile
    parser.parse(src)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 361, in endElementNS
    self.context.end()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 538, in end
    self.stack.pop().finish()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 686, in finish
    actions = self.handler(context, *_args)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Zope2-2.13.5-py2.6.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 550, in include
    processxmlfile(f, context)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 382, in processxmlfile
    parser.parse(src)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 361, in endElementNS
    self.context.end()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 538, in end
    self.stack.pop().finish()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 686, in finish
    actions = self.handler(context, *_args)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/z3c.autoinclude-0.3.3-py2.6.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/z3c.autoinclude-0.3.3-py2.6.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 550, in include
    processxmlfile(f, context)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 382, in processxmlfile
    parser.parse(src)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/plone/ploneinstalls/test4.1a3/Python-2.6/lib/python2.6/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/xmlconfig.py", line 361, in endElementNS
    self.context.end()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 538, in end
    self.stack.pop().finish()
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 685, in finish
    args = toargs(context, *self.argdata)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 1377, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/fields.py", line 139, in fromUnicode
    value = self.context.resolve(name)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/zope.configuration-3.7.2-py2.6.egg/zope/configuration/config.py", line 181, in resolve
    mod = __import__(mname, *_import_chickens)
  File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/collective.portlet.content-1.6-py2.6.egg/collective/portlet/content/vocabularies.py", line 4, in <module>
    from zope.app.schema.vocabulary import IVocabularyFactory
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/plone/ploneinstalls/test4.1a3/zinstance/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/Products.CMFPlone-4.1b1-py2.6.egg/Products/CMFPlone/configure.zcml", line 96.4-100.10
    ZopeXMLConfigurationError: File "/plone/ploneinstalls/test4.1a3/buildout-cache/eggs/collective.portlet.content-1.6-py2.6.egg/collective/portlet/content/configure.zcml", line 12.4-15.4
    ImportError: No module named schema.vocabulary

**Comment by khink** [comment]
Comment on original issue: "Added by Michael Smith on Jul 19, 2011 06:03 PM
Fixed inSVN trunk. I don't know in what revision it was fixed, but as of this date it works."

Issue is copied over here for completeness' sake.
